/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [appcompat website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * [core website](http://developer.android.com/tools/extras/support-library.html) */
    const val androidx_core_core: String = "androidx.core:core:" + Versions.androidx_core_core

    /**
     * [legacy-support-v4 website](http://developer.android.com/tools/extras/support-library.html) */
    const val legacy_support_v4: String =
            "androidx.legacy:legacy-support-v4:" + Versions.legacy_support_v4

    /**
     * [lifecycle-extensions website](https://developer.android.com/topic/libraries/architecture/index.html) */
    const val lifecycle_extensions: String =
            "androidx.lifecycle:lifecycle-extensions:" + Versions.androidx_lifecycle

    /**
     * [lifecycle-runtime website](https://developer.android.com/topic/libraries/architecture/index.html) */
    const val lifecycle_runtime: String =
            "androidx.lifecycle:lifecycle-runtime:" + Versions.androidx_lifecycle

    /**
     * [jetifier-processor website](http://developer.android.com/tools/extras/support-library.html) */
    const val jetifier_processor: String =
            "com.android.tools.build.jetifier:jetifier-processor:" + Versions.jetifier_processor

    /**
     * [aapt2 website](https://developer.android.com/studio) */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val com_android_tools_build_gradle: String =
            "com.android.tools.build:gradle:" + Versions.com_android_tools_build_gradle

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * [android-maven-gradle-plugin website](https://github.com/dcendents/android-maven-gradle-plugin) */
    const val android_maven_gradle_plugin: String =
            "com.github.dcendents:android-maven-gradle-plugin:" + Versions.android_maven_gradle_plugin

    const val kotlin_functional_extensions_android: String =
            "com.github.giacomoParisi.kotlin-functional-extensions:kotlin-functional-extensions-android:" + Versions.com_github_giacomoparisi_kotlin_functional_extensions

    const val kotlin_functional_extensions_arrow: String =
            "com.github.giacomoParisi.kotlin-functional-extensions:kotlin-functional-extensions-arrow:" + Versions.com_github_giacomoparisi_kotlin_functional_extensions

    const val kotlin_functional_extensions_core: String =
            "com.github.giacomoParisi.kotlin-functional-extensions:kotlin-functional-extensions-core:" + Versions.com_github_giacomoparisi_kotlin_functional_extensions

    const val kotlin_functional_extensions_coroutines: String =
            "com.github.giacomoParisi.kotlin-functional-extensions:kotlin-functional-extensions-coroutines:" + Versions.com_github_giacomoparisi_kotlin_functional_extensions

    /**
     * [dagger-android-processor website](https://github.com/google/dagger) */
    const val dagger_android_processor: String =
            "com.google.dagger:dagger-android-processor:" + Versions.com_google_dagger

    /**
     * [dagger-android-support website](https://github.com/google/dagger) */
    const val dagger_android_support: String =
            "com.google.dagger:dagger-android-support:" + Versions.com_google_dagger

    /**
     * [dagger-android website](https://github.com/google/dagger) */
    const val dagger_android: String =
            "com.google.dagger:dagger-android:" + Versions.com_google_dagger

    /**
     * [dagger-compiler website](https://github.com/google/dagger) */
    const val dagger_compiler: String =
            "com.google.dagger:dagger-compiler:" + Versions.com_google_dagger

    /**
     * [dagger website](https://github.com/google/dagger) */
    const val dagger: String = "com.google.dagger:dagger:" + Versions.com_google_dagger

    /**
     * [retrofit website](https://github.com/square/retrofit/) */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.retrofit

    const val arrow_annotations_processor: String =
            "io.arrow-kt:arrow-annotations-processor:" + Versions.io_arrow_kt

    const val arrow_core: String = "io.arrow-kt:arrow-core:" + Versions.io_arrow_kt

    const val arrow_data: String = "io.arrow-kt:arrow-data:" + Versions.io_arrow_kt

    const val arrow_instances_core: String =
            "io.arrow-kt:arrow-instances-core:" + Versions.io_arrow_kt

    const val arrow_instances_data: String =
            "io.arrow-kt:arrow-instances-data:" + Versions.io_arrow_kt

    const val arrow_syntax: String = "io.arrow-kt:arrow-syntax:" + Versions.io_arrow_kt

    /**
     * [arrow-typeclasses website](https://github.com/arrow-kt/arrow/) */
    const val arrow_typeclasses: String = "io.arrow-kt:arrow-typeclasses:" + Versions.io_arrow_kt

    /**
     * [rxandroid website](https://github.com/ReactiveX/RxAndroid) */
    const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

    /**
     * [rxjava website](https://github.com/ReactiveX/RxJava) */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * [kotlin-android-extensions-runtime website](https://kotlinlang.org/) */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-android-extensions website](https://kotlinlang.org/) */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-annotation-processing-gradle website](https://kotlinlang.org/) */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-jdk7 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk7: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlinx-coroutines-android website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.kotlinx_coroutines_android
}
